(()=>{
const demo={profiles:[
{id:'a1',display_name:'Sammie',email:'admin@example.com',role:'administrator',account_status:'active',created_at:'2026-09-01'},
{id:'t1',display_name:'Alex Morgan',email:'alex@coach.test',role:'trainer',account_status:'active',created_at:'2026-09-08'},
{id:'t2',display_name:'Jordan Lee',email:'jordan@coach.test',role:'trainer',account_status:'active',created_at:'2026-09-12'},
{id:'c1',display_name:'Maya Chen',email:'maya@example.com',role:'client',account_status:'active',created_at:'2026-09-15'},
{id:'c2',display_name:'Theo Hart',email:'theo@example.com',role:'client',account_status:'active',created_at:'2026-09-17'},
{id:'c3',display_name:'Nina Cole',email:'nina@example.com',role:'client',account_status:'active',created_at:'2026-09-19'}],rels:[
{id:'r1',status:'active',goal:'Strength + mobility',trainer:{id:'t1',display_name:'Alex Morgan'},client:{id:'c1',display_name:'Maya Chen'}},
{id:'r2',status:'trial',goal:'Calisthenics foundation',trainer:{id:'t1',display_name:'Alex Morgan'},client:{id:'c2',display_name:'Theo Hart'}},
{id:'r3',status:'active',goal:'Lifetime athleticism',trainer:{id:'t2',display_name:'Jordan Lee'},client:{id:'c3',display_name:'Nina Cole'}}],workouts:42,invites:2,subscriptions:[{client:'Maya Chen',plan:'Coaching Plus',amount:24900,status:'active',renewal:'18 Oct 2026'},{client:'Theo Hart',plan:'Coaching',amount:14900,status:'trialing',renewal:'25 Oct 2026'},{client:'Nina Cole',plan:'Premium',amount:39900,status:'active',renewal:'19 Oct 2026'}],payments:[{client:'Maya Chen',amount:24900,status:'paid'},{client:'Nina Cole',amount:39900,status:'paid'}]};
const $=s=>document.querySelector(s),view=$('#admin-view'),title=$('#page-title'),sub=$('#page-sub');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function roleLabel(r){return r==='administrator'?'Administrator':r[0].toUpperCase()+r.slice(1)}
function metrics(){const p=demo.profiles;return `<div class="metricgrid"><div class="card metric"><small>CLIENTS</small><strong>${p.filter(x=>x.role==='client').length}</strong><span>member accounts</span></div><div class="card metric"><small>TRAINERS</small><strong>${p.filter(x=>x.role==='trainer').length}</strong><span>coaching accounts</span></div><div class="card metric"><small>WORKOUTS</small><strong>${demo.workouts}</strong><span>recorded</span></div><div class="card metric"><small>PENDING INVITES</small><strong>${demo.invites}</strong><span>awaiting claim</span></div></div>`}
function overview(){title.textContent='Platform overview';sub.textContent='Operate the platform without stepping into day-to-day coaching.';view.innerHTML=metrics()+`<div class="split2" style="margin-top:16px"><section class="card section"><h3>Role boundaries</h3><p><b>Client</b> trains, logs and views their own progress.</p><p><b>Trainer</b> manages only assigned clients and coaching programmes.</p><p><b>Administrator</b> manages platform people, roles, relationships and operations.</p></section><section class="card section"><h3>System health</h3><p>✓ Role separation enabled</p><p>✓ Trainer-client assignment model</p><p>✓ Workout summaries isolated by client</p><p>✓ Role escalation blocked in browser</p></section></div>`}
function people(){title.textContent='People';sub.textContent='Account lifecycle, roles and access control.';view.innerHTML=`<section class="card section"><div class="toolbar"><input id="people-search" class="field" placeholder="Search name, email or role"><span class="notice">Demo controls mirror production Administrator permissions.</span></div><div style="overflow:auto"><table class="admin-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Controls</th></tr></thead><tbody id="people-body"></tbody></table></div></section>`;const body=$('#people-body');function render(){const q=$('#people-search').value.toLowerCase();body.innerHTML=demo.profiles.filter(x=>`${x.display_name} ${x.email} ${x.role}`.toLowerCase().includes(q)).map(x=>`<tr><td><b>${esc(x.display_name)}</b></td><td>${esc(x.email)}</td><td><span class="rolepill">${roleLabel(x.role)}</span></td><td><span class="rolepill">${esc(x.account_status||'active')}</span></td><td><div class="rowactions">${x.role==='administrator'?'<span class="rolepill">Protected</span>':`<button class="btn toggle-status" data-id="${x.id}">${x.account_status==='suspended'?'Reactivate':'Suspend'}</button>${x.role==='client'?`<button class="btn danger delete-client" data-id="${x.id}">Delete</button>`:''}`}</div></td></tr>`).join('');document.querySelectorAll('.toggle-status').forEach(b=>b.onclick=()=>{const x=demo.profiles.find(p=>p.id===b.dataset.id);x.account_status=x.account_status==='suspended'?'active':'suspended';render()});document.querySelectorAll('.delete-client').forEach(b=>b.onclick=()=>{const x=demo.profiles.find(p=>p.id===b.dataset.id);if(!confirm(`Delete ${x.display_name} from this demo?`))return;demo.profiles=demo.profiles.filter(p=>p.id!==x.id);demo.rels=demo.rels.filter(r=>r.client.id!==x.id);render()})}$('#people-search').oninput=render;render()}
function relationships(){title.textContent='Trainer ↔ Client';sub.textContent='Transfer, archive and reset client coaching relationships.';view.innerHTML=`<section class="card section"><div style="overflow:auto"><table class="admin-table"><thead><tr><th>Client</th><th>Trainer</th><th>Status</th><th>Goal</th><th>Controls</th></tr></thead><tbody>${demo.rels.map(r=>`<tr><td><b>${esc(r.client.display_name)}</b></td><td>${esc(r.trainer.display_name)}</td><td><span class="rolepill">${esc(r.status)}</span></td><td>${esc(r.goal)}</td><td><div class="rowactions"><button class="btn transfer-demo" data-id="${r.id}">Transfer</button><button class="btn reset-demo" data-id="${r.id}">Reset week</button><button class="btn danger archive-demo" data-id="${r.id}">Archive</button></div></td></tr>`).join('')}</tbody></table></div></section>`;document.querySelectorAll('.transfer-demo').forEach(b=>b.onclick=()=>{const r=demo.rels.find(x=>x.id===b.dataset.id),trainers=demo.profiles.filter(x=>x.role==='trainer'&&x.account_status!=='suspended');const names=trainers.map((t,i)=>`${i+1}. ${t.display_name}`).join('\n');const n=Number(prompt('Choose trainer:\n'+names));if(n>=1&&n<=trainers.length){r.trainer={id:trainers[n-1].id,display_name:trainers[n-1].display_name};relationships()}});document.querySelectorAll('.reset-demo').forEach(b=>b.onclick=()=>alert('Demo: active programme reset to Week 1.'));document.querySelectorAll('.archive-demo').forEach(b=>b.onclick=()=>{const r=demo.rels.find(x=>x.id===b.dataset.id);r.status='archived';relationships()})}
function programmes(){title.textContent='Programmes';sub.textContent='Platform visibility without changing a trainer’s client prescription by accident.';view.innerHTML=`<section class="card section"><h3>Human Movement OS · 52 Week</h3><p>Core programme template · 4 phases · 52 weeks.</p><div class="actions"><span class="btn ghost">Client App</span><span class="btn ghost">Trainer assignments</span><span class="btn ghost">Progress tracking</span></div></section>`}
function billing(){title.textContent='Billing & revenue';sub.textContent='Administrator controls financial operations; trainers only see client payment status.';const active=demo.subscriptions.filter(x=>x.status==='active'),mrr=active.reduce((a,x)=>a+x.amount,0),money=c=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(c/100);view.innerHTML=`<div class="metricgrid"><div class="card metric"><small>ACTIVE SUBSCRIPTIONS</small><strong>${active.length}</strong></div><div class="card metric"><small>DEMO MRR</small><strong>${money(mrr)}</strong></div><div class="card metric"><small>TRIALS</small><strong>${demo.subscriptions.filter(x=>x.status==='trialing').length}</strong></div><div class="card metric"><small>PAYMENT ISSUES</small><strong>0</strong></div></div><section class="card section" style="margin-top:16px"><h3>Subscriptions</h3><div style="overflow:auto"><table class="admin-table"><thead><tr><th>Client</th><th>Plan</th><th>Status</th><th>Monthly</th><th>Next date</th></tr></thead><tbody>${demo.subscriptions.map(x=>`<tr><td><b>${esc(x.client)}</b></td><td>${esc(x.plan)}</td><td><span class="rolepill">${esc(x.status)}</span></td><td>${money(x.amount)}</td><td>${esc(x.renewal)}</td></tr>`).join('')}</tbody></table></div><p class="notice">Demo only. Real charges stay disabled until Stripe test mode and webhook verification are configured.</p></section>`} function operations(){title.textContent='Operations';sub.textContent='Administrator-level lifecycle and governance controls.';view.innerHTML=`<div class="split2"><section class="card section"><h3>Account operations</h3><p>✓ Suspend / reactivate accounts</p><p>✓ Delete clients</p><p>✓ Transfer clients between trainers</p><p>✓ Archive coaching relationships</p><p>✓ Reset programme / onboarding</p></section><section class="card section"><h3>Governance</h3><p>✓ Role control</p><p>✓ Invite revocation</p><p>✓ Administrator audit trail</p><p>✓ Billing visibility + refunds</p><p>✓ Destructive actions require confirmation</p></section></div><p class="notice" style="margin-top:16px">This page is the GitHub Pages demo. Production actions execute through Supabase policies, RPCs and server-side functions.</p>`}
const renders={overview,people,relationships,programmes,billing,operations};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));renders[b.dataset.view]()});overview();
})();
