(async()=>{
'use strict';
const $=s=>document.querySelector(s),msg=t=>{const e=$('#msg');e.hidden=false;e.textContent=t},form=$('#form');
if(HMOBackend.mode!=='supabase'){msg('Live onboarding needs Supabase configuration.');return}
const me=await HMOBackend.me();if(!me){location.href='account.html?next=onboarding.html';return}if(me.role!=='client'){location.href=me.role==='administrator'?'administrator.html':'trainer.html';return}
const [sub,onboard]=await Promise.all([HMOBackend.mySubscription(),HMOBackend.myOnboarding()]);
const bill=$('#billing');const paid=['active','trialing'].includes(sub?.status);bill.innerHTML=paid?`<b>Plan ready</b><br>${sub?.plan?.name||'Subscription'} · ${sub.status}`:`<b>Plan not active yet</b><br>You can submit onboarding now, but training activation may wait until billing is ready. <a href="billing.html">Choose/manage plan</a>.`;document.querySelector('#step-pay').classList.toggle('done',paid);
if(onboard){$('#existing').hidden=false;$('#existing').className='statusbox '+(onboard.status==='review_needed'?'warn':'');$('#existing').innerHTML=`<b>Current onboarding status: ${onboard.status.replace('_',' ')}</b>${onboard.status==='approved'?'<br>Your trainer has activated your coaching. <a href="index.html">Open workout</a>.':onboard.status==='review_needed'?'<br>Your trainer will review this before progression is activated.':'<br>Your trainer has received your setup.'}`;form.goal.value=onboard.primary_goal||'';form.experience.value=onboard.experience_level||'';form.days.value=onboard.training_days_per_week||4;form.minutes.value=onboard.preferred_session_minutes||45;[...form.querySelectorAll('[name="equipment"]')].forEach(x=>x.checked=(onboard.equipment||[]).includes(x.value));if(onboard.readiness_response){const r=form.querySelector(`[name="readiness"][value="${onboard.readiness_response}"]`);if(r)r.checked=true}form.readinessNotes.value=onboard.readiness_notes||'';form.consentData.checked=!!onboard.consent_data;form.consentCoaching.checked=!!onboard.consent_coaching;document.querySelector('#step-setup').classList.add('done');if(onboard.status==='approved')document.querySelector('#step-review').classList.add('done')}
form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form);const equipment=[...form.querySelectorAll('[name="equipment"]:checked')].map(x=>x.value);try{const row=await HMOBackend.submitOnboarding({goal:fd.get('goal').trim(),experience:fd.get('experience'),days:Number(fd.get('days')),minutes:Number(fd.get('minutes')),equipment,readiness:fd.get('readiness'),readinessNotes:fd.get('readinessNotes').trim(),consentData:fd.get('consentData')==='on',consentCoaching:fd.get('consentCoaching')==='on'});msg(row.status==='review_needed'?'Submitted. Your trainer will review your readiness note before activating progression.':'Submitted to your trainer for activation.');setTimeout(()=>location.reload(),900)}catch(err){msg(err.message||String(err))}};
})().catch(e=>{document.querySelector('#msg').hidden=false;document.querySelector('#msg').textContent=e.message||String(e)});
