(async()=>{
'use strict';
const $=s=>document.querySelector(s),form=$('#form'),pages=[...document.querySelectorAll('.wizard-page')],steps=[...document.querySelectorAll('.step')];let page=0,live=window.HMOBackend?.mode==='supabase',existing=null;
const msg=t=>{const e=$('#msg');e.hidden=false;e.textContent=t};
const equipment=()=>[...form.querySelectorAll('[name="equipment"]:checked')].map(x=>x.value);
function validateCurrent(){const p=pages[page],required=[...p.querySelectorAll('[required]')];for(const el of required){if(el.type==='radio'){if(!form.querySelector(`[name="${el.name}"]:checked`)){el.focus();return false}}else if(el.type==='checkbox'){if(!el.checked){el.focus();return false}}else if(!el.value.trim()){el.focus();return false}}return true}
function updateSummary(){const fd=new FormData(form);$('#summary').innerHTML=`<div class="summaryitem"><small>Primary goal</small><b>${esc(fd.get('goal')||'—')}</b></div><div class="summaryitem"><small>Experience</small><b>${esc(fd.get('experience')||'—')}</b></div><div class="summaryitem"><small>Schedule</small><b>${esc(fd.get('days')||'—')} days · ${esc(fd.get('minutes')||'—')} min</b></div><div class="summaryitem"><small>Equipment</small><b>${esc(equipment().join(', ')||'Not listed')}</b></div><div class="summaryitem"><small>Readiness</small><b>${esc(fd.get('readiness')||'—')}</b></div>`}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function show(n){page=Math.max(0,Math.min(pages.length-1,n));pages.forEach((x,i)=>x.classList.toggle('active',i===page));steps.forEach((x,i)=>{x.classList.toggle('active',i===page);x.classList.toggle('done',i<page)});$('#progress-bar').style.width=((page+1)/pages.length*100)+'%';$('#back').disabled=page===0;$('#next').hidden=page===pages.length-1;$('#submit').hidden=page!==pages.length-1;if(page===pages.length-1)updateSummary();window.scrollTo({top:0,behavior:'smooth'})}
$('#next').onclick=()=>{if(!validateCurrent())return;show(page+1)};$('#back').onclick=()=>show(page-1);
if(!live){$('#demo-banner').hidden=false;$('#billing').innerHTML='<b>Demo mode</b><br>No payment or account connection is required for this preview. Your answers remain in this browser.';try{const x=JSON.parse(localStorage.getItem('dop.hmo.onboarding.demo')||'null');if(x){form.goal.value=x.goal||'';form.experience.value=x.experience||'';form.days.value=x.days||4;form.minutes.value=x.minutes||45;[...form.querySelectorAll('[name="equipment"]')].forEach(e=>e.checked=(x.equipment||[]).includes(e.value));const r=form.querySelector(`[name="readiness"][value="${x.readiness||''}"]`);if(r)r.checked=true;form.readinessNotes.value=x.readinessNotes||'';$('#existing').hidden=false;$('#existing').innerHTML='<b>Demo onboarding saved</b><br>You can edit it or open the Client App.'}}catch{}
}else{const me=await HMOBackend.me();if(!me){location.href='account.html?next=onboarding.html';return}if(me.role!=='client'){location.href=me.role==='administrator'?'administrator.html':'trainer.html';return}const [sub,onboard]=await Promise.all([HMOBackend.mySubscription(),HMOBackend.myOnboarding()]);existing=onboard;const paid=['active','trialing'].includes(sub?.status);$('#billing').innerHTML=paid?`<b>Plan ready</b><br>${esc(sub?.plan?.name||'Subscription')} · ${esc(sub.status)}`:`<b>Plan not active yet</b><br>You can complete onboarding now; activation may wait until billing is ready. <a href="billing.html">Manage plan</a>.`;if(onboard){$('#existing').hidden=false;$('#existing').className='statusbox '+(onboard.status==='review_needed'?'warn':'');$('#existing').innerHTML=`<b>Current status: ${esc(onboard.status.replace('_',' '))}</b>${onboard.status==='approved'?'<br>Your trainer has activated coaching. <a href="index.html">Open workout</a>.':onboard.status==='review_needed'?'<br>Your trainer will review this before progression is activated.':'<br>Your trainer has received your setup.'}`;form.goal.value=onboard.primary_goal||'';form.experience.value=onboard.experience_level||'';form.days.value=onboard.training_days_per_week||4;form.minutes.value=onboard.preferred_session_minutes||45;[...form.querySelectorAll('[name="equipment"]')].forEach(x=>x.checked=(onboard.equipment||[]).includes(x.value));const rr=form.querySelector(`[name="readiness"][value="${onboard.readiness_response||''}"]`);if(rr)rr.checked=true;form.readinessNotes.value=onboard.readiness_notes||'';form.consentData.checked=!!onboard.consent_data;form.consentCoaching.checked=!!onboard.consent_coaching}}
form.onsubmit=async e=>{e.preventDefault();if(!validateCurrent())return;const fd=new FormData(form),data={goal:(fd.get('goal')||'').trim(),experience:fd.get('experience'),days:Number(fd.get('days')),minutes:Number(fd.get('minutes')),equipment:equipment(),readiness:fd.get('readiness'),readinessNotes:(fd.get('readinessNotes')||'').trim(),consentData:fd.get('consentData')==='on',consentCoaching:fd.get('consentCoaching')==='on'};try{if(!live){localStorage.setItem('dop.hmo.onboarding.demo',JSON.stringify(data));msg('Demo onboarding saved. You can now open the Client App.');$('#submit').textContent='Saved ✓';setTimeout(()=>location.href='index.html?onboarded=1',700);return}const row=await HMOBackend.submitOnboarding(data);msg(row.status==='review_needed'?'Submitted. Your trainer will review your readiness note before activating progression.':'Submitted to your trainer for activation.');$('#submit').textContent='Submitted ✓';setTimeout(()=>location.reload(),900)}catch(err){msg(err.message||String(err))}};show(0);
})().catch(e=>{const m=document.querySelector('#msg');if(m){m.hidden=false;m.textContent=e.message||String(e)}});