(() => {
const KEY='dop.hmo.trainer.v02',BRIDGE_KEY='dop.hmo.bridge.v03';
const templates=[
 {id:'hmo52',name:'Human Movement OS · 52 Weeks',weeks:52,description:'Four-phase strength, mobility, flexibility and lifetime athleticism system.'},
 {id:'foundation12',name:'Movement Foundations · 12 Weeks',weeks:12,description:'Control, range, strength and tissue-capacity foundation.'},
 {id:'calisthenics12',name:'Calisthenics Foundation · 12 Weeks',weeks:12,description:'Pulling, pushing, compression and supported skill foundations.'}
];
const seed={clients:[
 {id:'c1',name:'Maya Chen',email:'maya@example.test',status:'active',goal:'Strength + mobility',program:'hmo52',week:7,startDate:'2026-08-14',adherence:88,last:'Yesterday',notes:'Ready to progress calf loading next review.',billing:'active'},
 {id:'c2',name:'Daniel Brooks',email:'daniel@example.test',status:'trial',goal:'General movement',program:'foundation12',week:2,startDate:'2026-09-18',adherence:75,last:'2 days ago',notes:'Keep sessions under 45 minutes during trial.',billing:'trialing'},
 {id:'c3',name:'Priya Shah',email:'priya@example.test',status:'active',goal:'Calisthenics + flexibility',program:'calisthenics12',week:5,startDate:'2026-08-28',adherence:94,last:'Today',notes:'Excellent consistency. Review handstand wall volume.',billing:'active'}
],activity:[{text:'Priya completed Saturday session',when:'Today'},{text:'Maya reached 88% four-week adherence',when:'Yesterday'},{text:'Daniel trial review due',when:'In 5 days'}]};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
let state=load(),selected=state.clients[0]?.id||null,filter='';
function bridgeSummaries(){try{return JSON.parse(localStorage.getItem(BRIDGE_KEY)||'[]')}catch{return []}}
function syncBridge(){
 const items=bridgeSummaries();let changed=false;
 state.clients.forEach(c=>{const logs=items.filter(x=>x.clientId===c.id).sort((a,b)=>Date.parse(b.completedAt)-Date.parse(a.completedAt));c.workouts=logs.slice(0,50);if(logs.length){const latest=logs[0];c.last=new Date(latest.completedAt).toLocaleString('en-AU',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'});const recent=logs.filter(x=>Date.now()-Date.parse(x.completedAt)<=28*86400000);const attempts=recent.length,done=recent.filter(x=>x.completed).length;c.adherence=attempts?Math.round(done/attempts*100):c.adherence;changed=true;}});
 if(changed)save();
}
syncBridge();window.addEventListener('storage',e=>{if(e.key===BRIDGE_KEY){syncBridge();render();}});window.addEventListener('focus',()=>{syncBridge();render();});

const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.add('hidden'),2200)}
function template(id){return templates.find(x=>x.id===id)||templates[0]}
function intelClient(c){return {id:c.id,client:{id:c.id,display_name:c.name,email:c.email},_workouts:(c.workouts||[]).map(w=>({completed:!!w.completed,completed_at:w.completedAt,duration_seconds:w.durationSeconds,completed_sets:w.completedSets,planned_sets:w.plannedSets,perceived_effort:w.effort})),_notes:c.notes?[{note:c.notes}]:[],_billing:{status:c.billing||'not set'},_onboarding:null};}
function intelClients(){return state.clients.map(intelClient)}
function initials(n){return n.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function statusBadge(s){return `<span class="badge ${esc(s)}">${esc(s[0].toUpperCase()+s.slice(1))}</span>`}
function kpis(){const active=state.clients.filter(c=>c.status==='active').length,trial=state.clients.filter(c=>c.status==='trial').length,avg=state.clients.length?Math.round(state.clients.reduce((a,c)=>a+c.adherence,0)/state.clients.length):0;return `<div class="grid kpis"><div class="card kpi"><span>Active clients</span><strong>${active}</strong><em>${trial} trial</em></div><div class="card kpi"><span>Average adherence</span><strong>${avg}%</strong><em>last 4 weeks</em></div><div class="card kpi"><span>Needs review</span><strong>${state.clients.filter(c=>c.adherence<80).length}</strong><em>attention queue</em></div><div class="card kpi"><span>Programs</span><strong>${templates.length}</strong><em>reusable templates</em></div></div>`}
function rows(){const q=filter.toLowerCase();return state.clients.filter(c=>!q||c.name.toLowerCase().includes(q)||c.email.toLowerCase().includes(q)).map(c=>`<tr class="client-row"><td><button class="namebtn" data-client="${c.id}">${esc(c.name)}</button><br><small style="color:var(--muted)">${esc(c.email)}</small></td><td>${statusBadge(c.status)}</td><td>${esc(template(c.program).name)}</td><td>Week ${c.week}</td><td><b>${c.adherence}%</b><div class="progress"><i style="width:${c.adherence}%"></i></div></td><td>${esc(c.last)}</td></tr>`).join('')||`<tr><td colspan="6">No matching clients.</td></tr>`}
function panel(){const c=state.clients.find(x=>x.id===selected);if(!c)return `<div class="empty"><div><h3>No client selected</h3><p>Select a client to view their coaching record.</p></div></div>`;const p=template(c.program);return `<div class="clienthead"><div class="avatar">${initials(c.name)}</div><div><h3>${esc(c.name)}</h3><p>${esc(c.email)}</p></div></div><div class="detailgrid"><div class="stat"><small>Status</small>${statusBadge(c.status)}</div><div class="stat"><small>Adherence</small><strong>${c.adherence}%</strong></div><div class="stat"><small>Billing</small><strong>${esc(c.billing||'not set')}</strong></div><div class="stat"><small>Current program</small><strong style="font-size:13px">${esc(p.name)}</strong></div><div class="stat"><small>Position</small><strong>Week ${c.week}/${p.weeks}</strong></div></div><div class="block"><label>Program assignment</label><div class="inline"><select class="field" id="edit-program">${templates.map(x=>`<option value="${x.id}" ${x.id===c.program?'selected':''}>${esc(x.name)}</option>`).join('')}</select><input class="field" id="edit-week" type="number" min="1" max="104" value="${c.week}"></div></div><div class="block"><label>Trainer note</label><textarea class="field" id="edit-note" maxlength="5000">${esc(c.notes||'')}</textarea></div><div class="actions" style="margin-top:12px"><button class="btn primary" data-action="save-client-detail">Save changes</button><button class="btn" data-action="open-workout">Open client workout</button><button class="btn" data-action="copy-invite">Copy invite link</button></div>${window.HMOIntelligenceUI?HMOIntelligenceUI.reviewHTML(intelClient(c)):''}<div class="block"><label>Recent workout results</label>${(c.workouts||[]).length?(c.workouts||[]).slice(0,5).map(w=>`<div class="activity"><article><b>${esc(w.title)} · ${w.completed?'Completed':'Partial'}</b><small>${new Date(w.completedAt).toLocaleString('en-AU')} · ${Math.round(w.durationSeconds/60)} min · ${w.completedSets} sets${w.effort?' · RPE '+w.effort:''}</small></article></div>`).join(''):'<p style="color:var(--muted)">No synced workouts yet.</p>'}</div>`}
function dashboard(){const intel=window.HMOIntelligenceUI?`<section class="intel-card"><div class="intel-head"><div><h3>Who needs my attention today?</h3><p>Local AI kit · evidence-backed signals · Trainer decides</p></div><span class="ai-chip">Ω VERIFIED ROUTING</span></div>${HMOIntelligenceUI.queueHTML(intelClients())}</section>`:'';return `${intel}${kpis()}<div class="layout"><section class="card section"><h3>Clients</h3><div class="toolbar"><input class="field search" id="search" placeholder="Search clients" value="${esc(filter)}"><select class="field" id="status-filter"><option>All statuses</option></select></div><div class="tablewrap"><table><thead><tr><th>Client</th><th>Status</th><th>Program</th><th>Week</th><th>Adherence</th><th>Last workout</th></tr></thead><tbody>${rows()}</tbody></table></div></section><aside class="card section client-panel">${panel()}</aside></div><section class="card section" style="margin-top:16px"><h3>Recent signals</h3><div class="activity">${state.activity.map(a=>`<article><b>${esc(a.text)}</b><small>${esc(a.when)}</small></article>`).join('')}</div></section>`}
function clientsView(){return `${kpis()}<section class="card section"><h3>All clients</h3><div class="toolbar"><input class="field search" id="search" placeholder="Search clients" value="${esc(filter)}"></div><div class="tablewrap"><table><thead><tr><th>Client</th><th>Status</th><th>Program</th><th>Week</th><th>Adherence</th><th>Last workout</th></tr></thead><tbody>${rows()}</tbody></table></div></section>`}
function programsView(){return `<section class="grid programs">${templates.map(p=>`<article class="card program"><div class="meta">${p.weeks} WEEKS</div><h4>${esc(p.name)}</h4><p>${esc(p.description)}</p><button class="btn" data-assign="${p.id}">Assign to client</button></article>`).join('')}</section>`}
function settingsView(){return `<section class="card section"><h3>Architecture status</h3><div class="notice"><b>Current preview:</b> ${window.HMOBackend?.mode==='supabase'?'Supabase mode':'local demo mode'}. The UI is fully interactive; production accounts require your Supabase project URL + publishable anon key.</div><div class="activity"><article><b>Authentication</b><small>Supabase Auth adapter included. Client is safest signup default.</small></article><article><b>Database</b><small>Profiles, trainer-client assignments, templates, program assignments, notes and workout summaries.</small></article><article><b>Security</b><small>Row-level security policies included in <code>supabase-schema.sql</code>.</small></article><article><b>Payments</b><small>Not connected in Gate 1 + 2. Stripe belongs in Gate 4 after account flow is proven.</small></article></div><div class="actions" style="margin-top:16px"><button class="btn danger" data-action="reset-demo">Reset demo data</button></div></section>`}
let view='dashboard';function render(){const map={dashboard:['Trainer dashboard','Who needs your attention today?',dashboard],clients:['Clients','Your active coaching roster.',clientsView],programs:['Programs','Build once. Assign and personalise.',programsView],settings:['Settings','Database and account architecture.',settingsView]};const [title,sub,fn]=map[view];$('#page-title').textContent=title;$('#page-sub').textContent=sub;$('#view').innerHTML=fn();document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));bindDynamic()}
function bindDynamic(){document.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>{selected=b.dataset.client;view='dashboard';render()});const s=$('#search');if(s)s.oninput=e=>{filter=e.target.value;const body=document.querySelector('tbody');if(body)body.innerHTML=rows();bindDynamic()};document.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>{openClientModal(b.dataset.assign)});document.querySelectorAll('[data-action="save-client-detail"]').forEach(b=>b.onclick=saveDetail);document.querySelectorAll('[data-action="copy-invite"]').forEach(b=>b.onclick=copyInvite);document.querySelectorAll('[data-action="open-workout"]').forEach(b=>b.onclick=openWorkout);document.querySelectorAll('[data-intel-client]').forEach(b=>b.onclick=()=>{selected=b.dataset.intelClient;view='dashboard';render();document.querySelector('.client-panel')?.scrollIntoView({behavior:'smooth',block:'start'})});document.querySelectorAll('[data-action="approve-ai-review"]').forEach(b=>b.onclick=approveAIReview);document.querySelectorAll('[data-action="dismiss-ai-review"]').forEach(b=>b.onclick=()=>toast('AI draft dismissed · no action taken'));document.querySelectorAll('[data-action="reset-demo"]').forEach(b=>b.onclick=()=>{if(confirm('Reset local Trainer Edition demo data?')){state=structuredClone(seed);selected=state.clients[0].id;save();render();toast('Demo reset')}})}
function approveAIReview(){const c=state.clients.find(x=>x.id===selected);if(!c)return;const r=HMOBrain.weeklyReview(intelClient(c));c.notes=`AI-assisted weekly review — trainer approved\n${r.summary}\nSuggested action: ${r.suggestedAction}\n${c.notes||''}`.trim();OmegaRuntime.audit('trainer_approved_ai_review',{client_id:c.id});save();render();toast('Approved review saved as trainer note')}
function saveDetail(){const c=state.clients.find(x=>x.id===selected);if(!c)return;c.program=$('#edit-program').value;c.week=Math.max(1,Math.min(template(c.program).weeks,Number($('#edit-week').value)||1));c.notes=$('#edit-note').value.trim();save();render();toast('Client updated')}
function openWorkout(){const c=state.clients.find(x=>x.id===selected);if(!c)return;saveDetail();const url=`index.html?client=${encodeURIComponent(c.id)}&trainer=1`;window.open(url,'_blank','noopener');toast(`Opened ${c.name}'s assigned workout`);}
async function copyInvite(){const c=state.clients.find(x=>x.id===selected);const link=new URL('index.html',location.href);link.searchParams.set('client',c.id);link.searchParams.set('invite','demo');const invite=link.href;try{await navigator.clipboard.writeText(invite);toast('Demo invite link copied')}catch{prompt('Copy this invite link',invite)}}
function openClientModal(program='hmo52'){const d=$('#client-modal'),f=$('#client-form');f.reset();f.startDate.value=new Date().toISOString().slice(0,10);$('#program-select').innerHTML=templates.map(x=>`<option value="${x.id}" ${x.id===program?'selected':''}>${esc(x.name)}</option>`).join('');d.showModal();setTimeout(()=>f.name.focus(),40)}
$('#client-form').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const id='c'+Date.now();state.clients.unshift({id,name:fd.get('name').trim(),email:fd.get('email').trim(),status:fd.get('status'),goal:fd.get('goal').trim(),program:fd.get('program'),week:1,startDate:fd.get('startDate'),adherence:0,last:'Not started',notes:''});selected=id;state.activity.unshift({text:`${fd.get('name').trim()} added to coaching roster`,when:'Just now'});save();$('#client-modal').close();view='dashboard';render();toast('Client created')});
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('#add-client').onclick=()=>openClientModal();$('#mobile-add').onclick=()=>openClientModal();
$('#mode-label').textContent=window.HMOBackend?.mode==='supabase'?'Supabase connected':'Demo database';render();
})();
